[package]
name = "vgaterm"
version = "0.1.0"
authors = ["dougli1sqrd, sethp"]
edition = "2021"
keywords = ["embedded", "esp32c3", "riscv", "terminal"]
repository = "https://github.com/rustbox/vgaterm"
license = "MIT"
readme = "README.md"

[lib]
name = "vgaterm"
path = "src/lib.rs"

[[bin]]
name = "vgaterm"
path = "src/main.rs"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
panic-halt = "0.2"
embedded-hal = "0.2"
esp32c3-hal = { git =  "https://github.com/esp-rs/esp-hal", features = ["direct-boot"] }
riscv = "0.8.0"
riscv-rt = "0.8.1"
nb = "1.0"