name: Check Cargo.lock

on:
  pull_request:
    branches: [main]
    paths:
    - Cargo.lock

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          Cargo.toml:
            - 'src/**'
    - if: steps.changes.outputs.Cargo.toml != 'true'
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message
      run: |
        echo ::warning file=Cargo.toml,line=1,endLine=1,col=1,endColumn=1,title=Cargo.lock changed!::Cargo.lock changed without observing a corresponding update to Cargo.toml

        /usr/bin/false
