on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - '!main'
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  # --------------------------------------------------------------------------
  # Check

  check:
    name: cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check --all-targets

  # --------------------------------------------------------------------------
  # Fmt

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: fmt --check

  # --------------------------------------------------------------------------
  # Clippy

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- --no-deps --all-targets
