on:
  push:
    branches:
      - "main"
jobs:
  fixup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1
    - uses: actions-rs/toolchain@v1

    - uses: actions-rs/cargo@v1
      with:
        command: fix
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore(fix): `cargo fix`'

    - uses: actions-rs/cargo@v1
      with:
        command: clippy --fix --all-targets
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore(fix): `cargo clippy --fix`'

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
    - uses: actions-rs/install@v0.1
      with:
        crate: taplo-cli
        use-tool-cache: true
    - run: taplo fmt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore(fmt): automated formatting'
